#pragma config(Sensor, dgtl1,  dataPin,        sensorDigitalIn)
#pragma config(Sensor, dgtl2,  readyPinIn,     sensorDigitalIn)
#pragma config(Sensor, dgtl3,  readyPinOut,    sensorDigitalOut)
#pragma config(Sensor, dgtl5,  led0,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  led1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  led2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  led3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  led4,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, led5,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, led6,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, led7,           sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define END_LENGTH 32

int receiveMessage();
void ready(bool status);
bool serverReady();
bool read();

int ledArray[] = {led0, led1, led2, led3, led4, led5, led6, led7};

task main()
{
	clearDebugStream();
	ready(0);
	wait1Msec(1000);
	while(true)
	{
		// Can take over transmission
		/*if(canSend() && needToSend)
		{
			sendMessage(message);
			endMessage();

			needToSend = false;
		}*/


		int message = receiveMessage();
		for(int i=0; i<8; i++)
			SensorValue(ledArray[i]) = 0;
		SensorValue(ledArray[message % 8]) = 1;
		writeDebugStreamLine("Received message: %d", message);
	}
}

int receiveMessage()
{
	int ctr = 0;
	int endCtr = 0;
	bool downloaded[400];

	//writeDebugStreamLine("Receiving message");
	while(ctr < 400)
	{
		ready(false);

		while(!serverReady())
		{
			// Can sleep here
		}

		// Read one bit
		downloaded[ctr] = read();
		writeDebugStream("%d", read());
		// Tell server we read a bit
		ready(true);

		if(downloaded[ctr] == 0)
			endCtr++;
		else
			endCtr = 0;

		if(endCtr == END_LENGTH)
			break;

		// Wait for server to acknowledge we read
		while(serverReady())
		{
		  // Can sleep here
		}

		// Tell server we are not trying to read anymore
		ready(false);

		ctr++;
	}

	// Read message up to index ctr - END_LENGTH which is the last real bit
  int message = 0;
	int power = 1;
	for(int i=0; i<=ctr-END_LENGTH; i++)
	{
		message += power * downloaded[i];
		power *= 2;
	}

	return message;
}

void ready(bool status)
{
	SensorValue[readyPinOut] = status;
}

bool serverReady()
{
	return SensorValue[readyPinIn] == 1;
}

bool read()
{
	return SensorValue[dataPin];
}
