#pragma config(Sensor, dgtl1,  dataPin,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  readyPinIn,     sensorDigitalIn)
#pragma config(Sensor, dgtl3,  readyPinOut,    sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int receiveMessage();
void ready(bool status);
bool serverReady();
bool read();

task main()
{
	while(true)
	{
		// Can take over transmission
		/*if(canSend() && needToSend)
		{
			sendMessage(message);
			endMessage();

			needToSend = false;
		}*/

		receiveMessage();
	}
}

int receiveMessage()
{
	int ctr = 0;
	int endCtr = 0;
	bool downloaded[400];

	while(ctr < 400)
	{
		ready(false);

		while(!serverReady())
		{
			// Can sleep here
		}

		// Read one bit
		downloaded[ctr] = read();
		// Tell server we read a bit
		ready(true);

		if(downloaded[ctr] == 0)
			endCtr++;
		else
			endCtr = 0;

		if(endCtr == 100)
			break;

		// Wait for server to acknowledge we read
		while(serverReady())
		{
		  // Can sleep here
		}

		// Tell server we are not trying to read anymore
		ready(false);

		ctr++;
	}

	// Read message up to index ctr - 100 which is the last real bit
	int message = 0;
	int power = 1;
	for(int i=ctr-100; i>=0; i--)
	{
		message += power * downloaded[i];
		power *= 2;
	}

	return message;
}

void ready(bool status)
{
	SensorValue[readyPinOut] = status;
}

bool serverReady()
{
	return SensorValue[readyPinIn] == 1;
}

bool read()
{
	return SensorValue[dataPin] == 1;
}
