#pragma config(Sensor, dgtl1,  dataPin,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  readyPinOut,    sensorDigitalOut)
#pragma config(Sensor, dgtl3,  readyPinIn,     sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void sendMessage(int m);
void endMessage();
bool canSend();
void ready(bool status);
bool clientReady();
void send(bool bit);

bool needToSend = false;
int message = 5;

task main()
{
	while(true)
	{
		// Can take over transmission
		if(canSend() && needToSend)
		{
			sendMessage(message);
			endMessage();

			needToSend = false;
		}
	}
}

void sendMessage(int m)
{
	for(; m > 0; m/=2)
	{
		// Send one bit of message
		send(m % 2);

		// Tell client the data is ready to be read
		ready(true);

		// Wait until client reads the data
		while(!clientReady())
		{
			// Could sleep here but see if it lowers transmission speed if you do
		}

		// Tell client we are ready to send again
		ready(false);

		// Wait until client is back to waiting for us to send
		while(clientReady())
		{
			// Could sleep here but see if it lowers transmission speed if you do
		}
	}
}

void endMessage()
{
	for(int i=0; i<100; i++)
	{
		// Send one bit of message
		send(0);

		// Tell client the data is ready to be read
		ready(true);

		// Wait until client reads the data
		while(!clientReady())
		{
			// Could sleep here but see if it lowers transmission speed if you do
		}

		// Tell client we are ready to send again
		ready(false);

		// Wait until client is back to waiting for us to send
		while(clientReady())
		{
			// Could sleep here but see if it lowers transmission speed if you do
		}
	}
}

bool canSend()
{
	return SensorValue[readyPinIn] == 0 && SensorValue[readyPinOut] == 0;
}

void ready(bool status)
{
	SensorValue[readyPinOut] = status;
}

bool clientReady()
{
	return SensorValue[readyPinIn] == 1;
}

void send(bool bit)
{
	SensorValue[dataPin] = bit;
}
